apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-buy-config
  namespace: simple-buy
data:
  # Database Configuration
  POSTGRES_USER: "simplebuy"
  POSTGRES_DB: "auth_db"

  # RabbitMQ Configuration
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.simple-buy:5672/"

  # Redis Configuration
  REDIS_URL: "redis://redis.simple-buy:6379/0"
  REDIS_NOTIFICATION_URL: "redis://redis.simple-buy:6379/1"

  # Service Ports
  AUTH_HTTP_PORT: "8081"
  AUTH_GRPC_PORT: "9081"
  PRODUCT_HTTP_PORT: "8082"
  PRODUCT_GRPC_PORT: "9082"
  CART_HTTP_PORT: "8083"
  CART_GRPC_PORT: "9083"
  ORDER_HTTP_PORT: "8084"
  ORDER_GRPC_PORT: "9084"
  NOTIFICATION_HTTP_PORT: "8085"
  NOTIFICATION_GRPC_PORT: "9085"

  # Service URLs
  PRODUCT_GRPC_URL: "product.simple-buy:9082"
  CART_GRPC_URL: "cart.simple-buy:9083"

  # Frontend Configuration
  NEXT_PUBLIC_API_URL: "http://localhost"
